spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    store-type: none
  messages:
    encoding: UTF-8
  output:
    ansi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.215.128:3306/UP_LORD?characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: h%7t*Feg&%
  mvc:
    # spring fox 3.0부터 엑츄에이터 때문에? ant_path_matcher를 사용해야 한다네요
    # 참고 링크
    # https://stackoverflow.com/questions/72465369/upgraded-spring-boot-to-2-7-0-failed-to-start-bean-documentationpluginsbootstr
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    session:
      persistent: true
      timeout: 0
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  shutdown: graceful
  forward-headers-strategy: native
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false
    whitelabel:
      enabled: false
  tomcat:
    additional-tld-skip-patterns: "*.jar"

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: uplord.uplordapi.dto , uplord.uplordapi.**.vo
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar

kakao:
  rest-api-key: "d8ffee0aed78643ac7c0644a387c1e2e"
  redirect-url: "http://localhost:3000/oauth"

jwt:
  header: "Authorization"
  secret-key: "ZINYECHUNGCHUNGDLQSLEKZINYECHUNGCHUNGDLQSLEK"
  token-validity-in-seconds: 1800000

